# Generated by Django 5.1.3 on 2025-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep2048', '0002_score_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
